Appdev3BAI/Controllers/BlobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Appdev3BAI.Models;
using Microsoft.Azure;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;

namespace Appdev3BAI.Controllers
{

    public class BlobsController : Controller
    {
        // GET: Blobs




        // GET: Blob
        
        public async System.Threading.Tasks.Task<ActionResult> Index(AppDevBusiness business)
        {
            return View(await business.GetPhotos("images"));
        }

        public ActionResult UploadView()
            {
                return View("Upload");
            }
            public ActionResult Upload(PhotoUpload photo, AppDevBusiness appbusiness, string studentnumber)
            {
                

                if (photo.FileUpload != null && photo.FileUpload.ContentLength > 0)
                {
                appbusiness.UploadPhoto("images", photo.FileUpload, studentnumber);
            }
            return RedirectToAction("Index");
            }


            public ActionResult Delete(string id, AppDevBusiness appdevbusiness)
            {
               
                if (ModelState.IsValid)

                {
                appdevbusiness.DeletePhoto("images", id);
                }
                return RedirectToAction("Index");
            }

        public async System.Threading.Tasks.Task<ActionResult> Details(string containername, string id)
        {
            CloudBlobContainer container = GetBlobContainer("images");
            CloudBlockBlob blockblob = container.GetBlockBlobReference(id);
            ViewModelBlobs vm = new ViewModelBlobs();
            AppDevBusiness appbusiness = new AppDevBusiness();
            vm.Name = blockblob.Name;
            vm.details = blockblob.Uri.ToString();
            Uri a = blockblob.Uri;
            vm.details =await appbusiness.detailsPic(a);
            return View(vm);

        }
        private static CloudBlobContainer GetBlobContainer(string containername)
        {

            var storageAccount = CloudStorageAccount.Parse(
                CloudConfigurationManager.GetSetting("StorageConnectionString"));

            var blobClient = storageAccount.CreateCloudBlobClient();

            var container = blobClient.GetContainerReference(containername);

            BlobContainerPermissions permissions = new BlobContainerPermissions
            {
                PublicAccess = BlobContainerPublicAccessType.Blob
            };

            container.CreateIfNotExists();

            container.SetPermissions(permissions);

            return container;
        }
    }
}

Appdev3BAI/Views/Blobs/Details.cshtml
@model Appdev3BAI.Models.ViewModelBlobs

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<head>
    <style>

        .card {
            box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            transition: 0.3s;
            width: 40%;
            border-radius: 5px;
        }

            .card:hover {
                box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
            }

        img {
            border-radius: 5px 5px 0 0;
        }

        .container {
            padding: 2px 16px;
        }

        </
    </style>

</head>
<div>
    <h4>ViewModelBlobs</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>*@

        @*<dt>
            @Html.DisplayNameFor(model => model.URI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.URI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.details)
        </dt>*@

       
        <div class="card">
            <img src="@Model.URI" alt="Avatar" style="width:100%"/>
            <div class="container">
                <h4><b>@Model.Name</b></h4>
                <p>@Model.details</p>
            </div>
        </div>
        @*<dd>
            @Html.DisplayFor(model => model.details)
        </dd>*@

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Appdev3BAI/Views/Blobs/Index.cshtml
@model IEnumerable<Appdev3BAI.Models.ViewModelBlobs>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div>
    <a href="@Href("~/Blobs/UploadView")">Upload Image</a>
</div>
<table class="table">
    @*<tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.URI)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.details)
        </th>
        <th></th>
    </tr>*@

@foreach (var item in Model) {
    <tr>
        @*<td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.URI)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.details)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>*@
        <td><a href="@item.URI" target="_blank">@item.Name</a><br /></td>

        <td> @Html.ActionLink("Delete", "Delete", new { id = item.Name })</td>
        <td> @Html.ActionLink("Details", "Details", new { id = item.Name })</td>
    </tr>
}

</table>

Appdev3BAI/Views/Blobs/Upload.cshtml
@model Appdev3BAI.Models.PhotoUpload

@{
    ViewBag.Title = "Upload";
}

<h2>Upload</h2>


@using (Html.BeginForm("Upload", "Blobs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>PhotoUpload</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.TextBoxFor(x => x.FileUpload, "", new { type = "file", @class = "form-control", accept = "image/jpeg,image/jpg" })
                @Html.ValidationMessageFor(model => model.FileUpload, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Image Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentNumber, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}